default: &default
  adapter: mysql2
  host: localhost
  encoding: utf8
  username: root
  password: rum4h4s1bjn
  pool: 5

development:
  <<: *default
  database: warehousing

test:
  <<: *default
  database: warehousing_test

production:
  adapter: mysql2
  host: localhost
  encoding: utf8
  username: rumahsib_bjn
  password: rum4h4s1bjn_p0rt4l
  pool: 5
  database: warehouse_development
