default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: sowo_user
  password: 123456
  pool: 5

development:
  <<: *default
  database: warehousing

test:
  <<: *default
  database: warehousing_test

# production:
#   <<: *default
#   host: localhost
#   database: warehouse_development
#   username: sowo_user
#   password: 123456
